# Generated by Django 5.2.13 on 2026-05-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorpersonrelationship',
            options={'ordering': ['-is_active', 'vendor__company__name', 'person__last_name']},
        ),
    ]
