# Generated by Django 5.2.13 on 2026-05-04 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='risk_rating',
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('credit', 'Credit'), ('integrity', 'Integrity'), ('sanctions', 'Sanctions'), ('cyber', 'Cyber'), ('geopolitical', 'Geopolitical')], max_length=20)),
                ('inherent_rating', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=20)),
                ('residual_rating', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='vendors.assessment')),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('assessment', 'category')},
            },
        ),
    ]
