# Generated by Django 5.2.13 on 2026-05-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_assessment_risk_rating_riskscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Risk',
        ),
    ]
