# Generated by Django 5.2.13 on 2026-05-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_delete_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='category',
            field=models.CharField(choices=[('credit', 'Credit risk'), ('integrity', 'Integrity risk'), ('sanctions', 'Sanctions risk'), ('cyber', 'Cyber risk'), ('geopolitical', 'Geopolitical risk')], default='credit', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='inherent_rating',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='residual_rating',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('under_review', 'Under review'), ('offboarded', 'Offboarded')], default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='RiskScore',
        ),
    ]
