# Generated by Django 5.2.13 on 2026-05-05 21:20

from django.db import migrations, models


def backfill_vendor_ids(apps, schema_editor):
    Vendor = apps.get_model('vendors', 'Vendor')
    for vendor in Vendor.objects.order_by('pk'):
        vendor.vendor_id = f"VND-{vendor.pk:04d}"
        vendor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_assessment_category_assessment_inherent_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.RunPython(backfill_vendor_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
